name: TestWorkflow-001
on: push
jobs:
    Setting-Environment:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Run some Tests
              run: npm test